name: weight_track_app
description: Weight Track App
publish_to: "none"
version: 1.1.1+11

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # OneSignal
  onesignal_flutter: ^3.5.0

  # Date
  intl: ^0.18.0

  # Date Picker
  scroll_date_picker: ^3.7.0

  # Storage
  shared_preferences: ^2.0.20

  # Firebase
  firebase_core: ^2.9.0

  # Line Chart
  syncfusion_flutter_charts: ^21.1.38

  # Splash Screen
  flutter_native_splash: ^2.2.19

flutter_native_splash:
  color: "#6200EE"
  image: assets/images/play_store_512.png
  fullscreen: true

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
